version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfiles/nest-app.dockerfile
    image: nestjs-app
    env_file:
      - ./.env
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
